Refactored Find JVM to use functional programming.
DuarteMRAlves/JavaCall.jl pull request #1
Opened 2021-05-05 20:33 UTC by DuarteMRAlves

2021-05-07 23:46 UTC, tosmarcel requested changes

2021-05-07 23:46 UTC, tosmarcel commented on src/jvm.jl
> +            ];
MacOS specific extension in error message

2021-05-07 23:46 UTC, tosmarcel commented on src/jvm.jl
> +        libpath = joinpath(directory,"jvm.dll")
Leftover macos-specific definition

2021-05-08 10:41 UTC, DuarteMRAlves commented on src/jvm.jl
> +            ];
Replaced file with variable set for each system

2021-05-08 10:41 UTC, DuarteMRAlves commented on src/jvm.jl
> +        libpath = joinpath(directory,"jvm.dll")
Removed definition

2021-05-08 15:59 UTC, tosmarcel commented on src/jvm.jl
> +            "Cannot find java library "*libfile*"\n",
```suggestion
            "Cannot find java library $(libfile)\n",
```

2021-05-08 15:59 UTC, tosmarcel approved these changes

2021-05-08 16:07 UTC, merged